#  Flight Delay & Cancellation Analysis
## Week 2: Know your data

### Course: 24ADI204 – Data Science and Visualization
### Project Type: Hack-A-BIT (Visual Storytelling Challenge)

---



> **Note:**
> No data cleaning or transformations are performed in this phase.
> The goal is *pure data understanding*.

# Import Required Libraries and Improve dataframe display for better readability

In [25]:

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

print("Libraries imported successfully.")

Libraries imported successfully.

# This  is to Load Raw Dataset

In [26]:
# Load the raw flight dataset
df = pd.read_csv("../Dataset/raw/raw_flights_01.csv")

# Display the first 5 rows to verify successful loading
df.head()

,YEAR,MONTH,DAY_OF_MONTH,OP_UNIQUE_CARRIER,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,CANCELLED,DIVERTED,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2024,1,1,9E,10135,1013506,30135,ABE,"Allentown/Bethlehem/Easton, PA",10397,1039707,30397,ATL,600,558.0,-2.0,832,757.0,-35.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
1,2024,1,1,9E,10135,1013506,30135,ABE,"Allentown/Bethlehem/Easton, PA",10397,1039707,30397,ATL,1231,1240.0,9.0,1450,1437.0,-13.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
2,2024,1,1,9E,10185,1018502,30185,AEX,"Alexandria, LA",10397,1039707,30397,ATL,600,555.0,-5.0,850,821.0,-29.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
3,2024,1,1,9E,10185,1018502,30185,AEX,"Alexandria, LA",10397,1039707,30397,ATL,1631,1620.0,-11.0,1917,1851.0,-26.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,2024,1,1,9E,10208,1020803,30208,AGS,"Augusta, GA",10397,1039707,30397,ATL,1849,1845.0,-4.0,2010,1947.0,-23.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN


# Dataset Size

In [27]:

df.shape

(1797381, 26)

#  Column Names

In [28]:
df.columns

Index(['YEAR', 'MONTH', 'DAY_OF_MONTH', 'OP_UNIQUE_CARRIER', 'ORIGIN_AIRPORT_ID', 'ORIGIN_AIRPORT_SEQ_ID',
       'ORIGIN_CITY_MARKET_ID', 'ORIGIN', 'ORIGIN_CITY_NAME', 'DEST_AIRPORT_ID', 'DEST_AIRPORT_SEQ_ID',
       'DEST_CITY_MARKET_ID', 'DEST', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY',
       'CANCELLED', 'DIVERTED', 'CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY',
       'LATE_AIRCRAFT_DELAY'],
      dtype='object')


#  Data Dictionary

In [29]:
data_dictionary = pd.DataFrame({
    "Column_Name": df.columns,
    "Data_Type": df.dtypes.values
})
data_dictionary

              Column_Name Data_Type
0                    YEAR     int64
1                   MONTH     int64
2            DAY_OF_MONTH     int64
3       OP_UNIQUE_CARRIER    object
4       ORIGIN_AIRPORT_ID     int64
5   ORIGIN_AIRPORT_SEQ_ID     int64
6   ORIGIN_CITY_MARKET_ID     int64
7                  ORIGIN    object
8        ORIGIN_CITY_NAME    object
9         DEST_AIRPORT_ID     int64
10    DEST_AIRPORT_SEQ_ID     int64
11    DEST_CITY_MARKET_ID     int64
12                   DEST    object
13           CRS_DEP_TIME     int64
14               DEP_TIME   float64
15              DEP_DELAY   float64
16           CRS_ARR_TIME     int64
17               ARR_TIME   float64
18              ARR_DELAY   float64
19              CANCELLED   float64
20               DIVERTED   float64
21          CARRIER_DELAY   float64
22          WEATHER_DELAY   float64
23              NAS_DELAY   float64
24         SECURITY_DELAY   float64
25    LATE_AIRCRAFT_DELAY   float64

In [30]:
data_dictionary.to_csv("../Reports/Data_Dictionary.csv", index=False)

#  Dataset Information

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1797381 entries, 0 to 1797380
Data columns (total 26 columns):
 #   Column                 Dtype
---  ------                 -----
 0   YEAR                   int64
 1   MONTH                  int64
 2   DAY_OF_MONTH           int64
 3   OP_UNIQUE_CARRIER      object
 4   ORIGIN_AIRPORT_ID      int64
 5   ORIGIN_AIRPORT_SEQ_ID  int64
 6   ORIGIN_CITY_MARKET_ID  int64
 7   ORIGIN                 object
 8   ORIGIN_CITY_NAME       object
 9   DEST_AIRPORT_ID        int64
 10  DEST_AIRPORT_SEQ_ID    int64
 11  DEST_CITY_MARKET_ID    int64
 12  DEST                   object
 13  CRS_DEP_TIME           int64
 14  DEP_TIME               float64
 15  DEP_DELAY              float64
 16  CRS_ARR_TIME           int64
 17  ARR_TIME               float64
 18  ARR_DELAY              float64
 19  CANCELLED              float64
 20  DIVERTED               float64
 21  CARRIER_DELAY          float64
 22  WEATHER_DELAY          float64
 23  NAS_DELAY              float64
 24  SECURITY_DELAY         float64
 25  LATE_AIRCRAFT_DELAY    float64
dtypes: float64(11), int64(11), object(4)
memory usage: 356.5+ MB

#  Statistical Summary

In [32]:
df.describe()

,YEAR,MONTH,DAY_OF_MONTH,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,CANCELLED,DIVERTED,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
count,1797381.0,1.797381e+06,1.797381e+06,1.797381e+06,1.797381e+06,1.797381e+06,1.797381e+06,1.797381e+06,1.797381e+06,1.797381e+06,1.753573e+06,1.753464e+06,1.797381e+06,1.751931e+06,1.747822e+06,1.797381e+06,1.797381e+06,388616.000000,388616.000000,388616.000000,388616.000000,388616.000000
mean,2024.0,6.200428e+00,1.598431e+01,1.264604e+04,1.264608e+06,3.173541e+04,1.264607e+04,1.264611e+06,3.173546e+04,1.326450e+03,1.330734e+03,1.447445e+01,1.489505e+03,1.459908e+03,9.020249e+00,2.506146e-02,2.511432e-03,27.184395,4.669715,12.500013,0.134681,30.363418
std,0.0,3.661152e+00,8.883970e+00,1.532416e+03,1.532414e+05,1.323210e+03,1.532405e+03,1.532403e+05,1.323220e+03,4.926114e+02,5.095994e+02,5.987619e+01,5.192382e+02,5.467474e+02,6.184155e+01,1.563119e-01,5.005123e-02,79.962154,36.282630,29.291973,3.506715,64.902773
min,2024.0,1.000000e+00,1.000000e+00,1.013500e+04,1.013506e+06,3.007000e+04,1.013500e+04,1.013506e+06,3.007000e+04,1.000000e+00,1.000000e+00,-6.600000e+01,1.000000e+00,1.000000e+00,-9.100000e+01,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2024.0,1.000000e+00,8.000000e+00,1.129200e+04,1.129202e+06,3.062700e+04,1.129200e+04,1.129202e+06,3.062700e+04,9.050000e+02,9.090000e+02,-6.000000e+00,1.102000e+03,1.044000e+03,-1.500000e+01,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2024.0,7.000000e+00,1.600000e+01,1.288900e+04,1.288904e+06,3.145300e+04,1.288900e+04,1.288904e+06,3.145300e+04,1.320000e+03,1.325000e+03,-2.000000e+00,1.516000e+03,1.502000e+03,-6.000000e+00,0.000000e+00,0.000000e+00,4.000000,0.000000,0.000000,0.000000,4.000000
75%,2024.0,1.000000e+01,2.400000e+01,1.402700e+04,1.402702e+06,3.246700e+04,1.402700e+04,1.402702e+06,3.246700e+04,1.735000e+03,1.746000e+03,1.100000e+01,1.925000e+03,1.918000e+03,1.100000e+01,0.000000e+00,0.000000e+00,23.000000,0.000000,16.000000,0.000000,36.000000
max,2024.0,1.000000e+01,3.100000e+01,1.686900e+04,1.686902e+06,3.599100e+04,1.686900e+04,1.686902e+06,3.599100e+04,2.359000e+03,2.400000e+03,3.777000e+03,2.359000e+03,2.400000e+03,3.803000e+03,1.000000e+00,1.000000e+00,3689.000000,1804.000000,1431.000000,1005.000000,2305.000000

# Missing Value Analysis

In [33]:
missing_counts = df.isnull().sum()
missing_df = pd.DataFrame({
    "Column_Name": missing_counts.index,
    "Missing_Count": missing_counts.values
}).sort_values(by="Missing_Count", ascending=False)

missing_df

              Column_Name  Missing_Count
25    LATE_AIRCRAFT_DELAY        1408765
24         SECURITY_DELAY        1408765
23              NAS_DELAY        1408765
22          WEATHER_DELAY        1408765
21          CARRIER_DELAY        1408765
18              ARR_DELAY          49559
17               ARR_TIME          45450
15              DEP_DELAY          43917
14               DEP_TIME          43808
1                   MONTH              0
20               DIVERTED              0
19              CANCELLED              0
16           CRS_ARR_TIME              0
0                    YEAR              0
12                   DEST              0
11    DEST_CITY_MARKET_ID              0
10    DEST_AIRPORT_SEQ_ID              0
9         DEST_AIRPORT_ID              0
8        ORIGIN_CITY_NAME              0
7                  ORIGIN              0
6   ORIGIN_CITY_MARKET_ID              0
5   ORIGIN_AIRPORT_SEQ_ID              0
4       ORIGIN_AIRPORT_ID              0
3       OP_UNIQUE_CARRIER              0
2            DAY_OF_MONTH              0
13           CRS_DEP_TIME              0

#  Missing Value Percentage

In [34]:
missing_df["Missing_Percentage"] = (missing_df["Missing_Count"] / len(df)) * 100

missing_df

              Column_Name  Missing_Count  Missing_Percentage
25    LATE_AIRCRAFT_DELAY        1408765           78.378763
24         SECURITY_DELAY        1408765           78.378763
23              NAS_DELAY        1408765           78.378763
22          WEATHER_DELAY        1408765           78.378763
21          CARRIER_DELAY        1408765           78.378763
18              ARR_DELAY          49559            2.757290
17               ARR_TIME          45450            2.528679
15              DEP_DELAY          43917            2.443388
14               DEP_TIME          43808            2.437324
1                   MONTH              0            0.000000
20               DIVERTED              0            0.000000
19              CANCELLED              0            0.000000
16           CRS_ARR_TIME              0            0.000000
0                    YEAR              0            0.000000
12                   DEST              0            0.000000
11    DEST_CITY_MARKET_ID              0            0.000000
10    DEST_AIRPORT_SEQ_ID              0            0.000000
9         DEST_AIRPORT_ID              0            0.000000
8        ORIGIN_CITY_NAME              0            0.000000
7                  ORIGIN              0            0.000000
6   ORIGIN_CITY_MARKET_ID              0            0.000000
5   ORIGIN_AIRPORT_SEQ_ID              0            0.000000
4       ORIGIN_AIRPORT_ID              0            0.000000
3       OP_UNIQUE_CARRIER              0            0.000000
2            DAY_OF_MONTH              0            0.000000
13           CRS_DEP_TIME              0            0.000000

#  Duplicate Record Check

In [35]:
duplicate_count = df.duplicated().sum()
duplicate_count

np.int64(0)

### Duplicate Record Observation
- Duplicate rows indicate redundancy in real-world flight data.
- These will be handled during the data cleaning phase (Week 2).

# Save Data Quality Report

In [36]:
missing_df.to_csv("../Reports/Data_Quality_Report.csv", index=False)
print(" Data Quality Report saved successfully.")

 Data Quality Report saved successfully.

In [37]:
data_quality_summary = {
    "Total Rows": df.shape[0],
    "Total Columns": df.shape[1],
    "Total Missing Values": df.isnull().sum().sum(),
    "Duplicate Rows": duplicate_count
}
data_quality_summary

{'Total Rows': 1797381,
 'Total Columns': 26,
 'Total Missing Values': np.int64(7226559),
 'Duplicate Rows': np.int64(0)}

In [38]:
# Save summary
pd.DataFrame(
    list(data_quality_summary.items()),
    columns=["Metric", "Value"]
).to_csv("../Reports/Data_Quality_Summary.csv", index=False)

## Week 2 Observations & Conclusion

- The dataset is large-scale and real-world in nature.
- Several columns contain missing values.
- Duplicate records are present.
- Both numerical and categorical attributes exist.

**Next Phase:**
Week 3 will focus on handling missing values using appropriate strategies.